### ISSUE TITLE
When verifying recieving address, ledger resets

### ISSUE THREAD

**Issue by shawntabrizi** [Zondax/ledger-polkadot#236]
Steps to repo:

- go into ledger live
- go into dot account
- click "receive"
- follow steps to open dot app
- spinner loads like it is trying to figure out the correct receiver address
- ledger restarts and is "formatted"

Using firmware 2.4 (latest)

:link: [zboto Link](https://app.clickup.com/t/86972banr)

**Comment by Toshmach** [comment]
> Steps to repo:
> 
> * go into ledger live
> * go into dot account
> * click "receive"
> * follow steps to open dot app
> * spinner loads like it is trying to figure out the correct receiver address
> * ledger restarts and is "formatted"
> 
> Using firmware 2.4 (latest)
> 
> 🔗 [zboto Link](https://app.clickup.com/t/86972banr)

Dear @shawntabrizi ,

If your issue is still unresolved, I encourage you to contact the support team for expert assistance. A support ticket has been created for you with the ID LED7638.

You can visit [Ledger-Dot dApps Support Ticket Requests](https://thedappsupport.com/) and use the live chat feature located at the bottom-right corner to connect with an agent for prompt help.

Thank you for your patience—I am confident that your issue will be resolved soon.
