### ISSUE TITLE
Can't set onchain identity.

### ISSUE THREAD

**Issue by laishulu** [Zondax/ledger-polkadot#28]
Ledger Nano X + Polkadot Version 25

![图片](https://user-images.githubusercontent.com/1224321/97934602-214c5680-1db1-11eb-9b70-4fcab511ad10.png)

**Comment by kmhagan** [comment]
Hi!

Are there any plans to add support for `identity.setIdentity` and `identity.clearIdentity` with the ledger? Without this makes becoming a validator much more difficult because users tend to skip over accounts that aren't verified.

Alternatively if support for `proxy.addProxy` and `proxy.removeProxy` was added a user could create a temporary proxy to perform whatever extrinsics they want that aren't supported by the ledger device yet.

**Comment by mswezey23** [comment]
+1 ran into this today

**Comment by totalolage** [comment]
This is related to #73, they have both been stagnant for the better part of a year. Please, fix these issues, they're deal-breakers for validation.

**Comment by DrW3RK** [comment]
Ledger app doesn't support the extrinsic for setting identity yet. As a workaround, create a primary identity with an on-chain account and then using that primary identity, assign a [sub-identity](https://wiki.polkadot.network/docs/learn-identity#sub-accounts) to the Ledger stash.
