### ISSUE TITLE
Question: Trying to make app work with dev chain

### ISSUE THREAD

**Issue by lovesh** [Zondax/ledger-polkadot#46]
In the pursuit of using Ledger wallet for [our Substrate chain](https://github.com/docknetwork/dock-substrate) (a fork of node-template), I tried making it work with our dev chain. With mostly chain-specific (decimal count, genesis hash, etc) modifications to the app as shown in [this commit](https://github.com/lovesh/ledger-polkadot/commit/1e48704ada3ea7537457b37cb12487e5cae75b54) and polkadot-js apps UI (details of the modifications in [this issue](https://github.com/polkadot-js/apps/issues/4225#issue-769032213) if you care), I was able to get a Ledger account added and a balance transfer done **but** I had to comment out the following lines from `_readTx` in `parser_iml.c` as you can see in [my commit](https://github.com/lovesh/ledger-polkadot/commit/1e48704ada3ea7537457b37cb12487e5cae75b54#diff-ffb67fa73b9d9db123fedd29975e52dd847cac4d797cf31f2763571735ac547dR380).

```
if (c->offset < c->bufferLen) {
    return parser_unexpected_unparsed_bytes;
}
```

From what I understand, this check ensures that the app is not getting any extra data in the transaction that it is not expecting, is that correct? 

- Can there be any bad implications of not having this check?
- Any pointers on how to find out what extra data is being sent that the app is not expecting? I am able to get the raw txn bytes sent from the browser but don't know how to debug in the app itself?
- Don't have much exp. with C or hardware programming so any pointers would be helpful.

**Comment by jleni** [comment]
Due to substrate design, there is a direct relation between metadata and the parser.
It is VERY likely that your fork is not compatible with this app. Data types are serialized by substrate based on the source code of the substrate chain and require a substantial amount of review. Metadata structure is very similar and can result in index changes. The code you remove is very critical, I would not recommend removing this. 

Just to clarify, the app is open source for clarity, openness and transparency, however, we don't recommend forking and adjusting without a deep understanding of the implications.
