### ISSUE TITLE
polkadot.js question

### ISSUE THREAD

**Issue by pale-face** [Zondax/ledger-polkadot#60]
So I have a bit of an issue.  I attached my ledger in polkadot.js, and if you don't have "only this network" checked for the account, it apparently adds that account across all networks, but with different addresses. Under Kusama, it shows this polkadot account but with a Kusama wallet address, so I accidentally sent KSM to this address. But my problem now is when I have Kusama open I cant sign the transaction to send them to another wallet, with my ledger, because its wanting me to open the Kusama app in my ledger. But that is a different account with its own set of private keys. What I think needs to be done is, I have to sign the Kusama transaction with the polkadot app on the ledger, since that wallet has the private keys for the Kusama wallet I sent my KSM too. I hope that wasn't too confusing, its a bit difficult for me to explain, since I am fairly knew to this technology. Any help or info would be appreciated on what to do next.

Thanks.

**Comment by Ray-zin** [comment]
Hello pale-face,
i do have a similar issue, but maybe i can help you at first. Have you tried to add another ledger account via tha Kusama App? I did have the same issue and that fixed it for me. Now it shows me two ledger accounts and i can use one for DOT and one for KSM (two adresses on the same Ledger device).

I didn't have checked "only this network" too and therefore i have a ledger account on the Darwinia Network (also found via subscan if i enter my Kusama adress). So i thought, i could use it for my RING tokens and start staking. So i sent my RING tokens to this account. But now i have the problem that neither the Polkadot App nor the Kusama App works in order to sign anything i want to do with the Ring tokens Therefore i'm unable to stake or send the Ring tokens to another account. I assume, we need a Ledger App for the Darwinia Network first so that the Darwinia chain is recognised by the Ledger? Or is it possible to add those chains to the Polkadot or Kusama App so we could sign the actions on the Darwinia Network with those apps too?

Thank you very much!

Greetings,
Ray

**Comment by pale-face** [comment]
Just want to update this, a new version of the Polkadot and Kusama ledger app was released, it allows you to use the polkadot keys on the Kusama network and vice versa in polkadot.js, and that fixed my issue. I was able to then retrieve my Kusama tokens that I accidentally sent to the DOT ledger address! Im so happy they came up with this fix.
