### ISSUE TITLE
Session.Setkeys (Not Supported)

### ISSUE THREAD

**Issue by paradoxxx-tt** [Zondax/ledger-polkadot#77]
Good day,

I am trying to submit my session_key to a stash in which both the controller and stash accounts reside on the ledger.  When I attempt to do so I receive an error that session.setkeys isn't supported.  I have successfully used this extrinsic on Kusama.

My app version is 6.28.0

Any help would be appreciated.

**Comment by mintho** [comment]
Same issue here. It used to work. Previously I was able to set a session key via my controller account that was sitting on my ledger. Now it doesn't work anymore.

**Comment by paradoxxx-tt** [comment]
I just used the setKeys extrinsic on Kusama without issue.  There seems to be a mismatch between the apps (Kusama vs Polkadot).

**Comment by mav137** [comment]
Also have this problem: Stash & Controller are the same ledger address. I try to set the session key, but displays an error about set.sessionkeys not being supported. Running V 7.30.0 on Ledger Nano S and js: apps v0.91.3-3

I'm running into this situation because I'm switching from being a nominator to a validator and tried to change the controller account to not be the same as the stash account (ledger), unfortunataly this is also not supported (stakingset.Controller not supported). My second thought was to leave the stash and controller to the same address and move forward with setting the session key. No luck, as described above. This leaves me unable to change my current setup. Only alternative is to unbond (takes me 30days and costs a lot of money) or stick to nominating. I'd appreciate if someone can take a look. Thanks!

**Comment by jleni** [comment]
This is now included. Readme.md and testcases has been updated too (https://github.com/Zondax/ledger-polkadot/blob/master/tests/testcases_current.json#L4710)

**Comment by jleni** [comment]
The new release has been submitted to ledger in PR https://github.com/LedgerHQ/app-polkadot/pull/9

**Comment by mav137** [comment]
Thanks guys, I'll be watching ledgers releases
